DECLARE    
    CURSOR REC_CUSTOMERS IS
    SELECT L.LOANID,L.CUSTOMERID,L.ENDDATE, C.NAME
    FROM LOANS L JOIN CUSTOMERS C
    ON L.CUSTOMERID = C.CUSTOMERID
    WHERE L.ENDDATE BETWEEN SYSDATE AND (SYSDATE + 30);

BEGIN
    FOR REC IN REC_CUSTOMERS LOOP
        DBMS_OUTPUT.PUT_LINE('Reminder: Loan ID ' || rec.LoanID || ' for customer "' || rec.Name || '" is due on ' || TO_CHAR(rec.EndDate, 'DD-Mon-YYYY'));
    END LOOP;

END;
/
